POST http://localhost:3001/api/cards HTTP/1.1
Content-Type: application/json

{
    "company": "Topps",
    "description": "Poole rookie Card",
    "notes": "Autographed",
    "service": "Super Express",
    "status": "Pending",
    "userId":"63e57076274bac783fa9a412"
}